# Generated by Django 6.0.6 on 2026-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
    ]
