# Generated by Django 6.0.6 on 2026-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_person_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('person', 'Person Detected'), ('motion', 'Motion Detected'), ('abandoned_object', 'Abandoned Object')], default='person', max_length=20),
        ),
    ]
