# Generated by Django 6.0.6 on 2026-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('person', 'Person Detected'), ('motion', 'Motion Detected'), ('abandoned_object', 'Abandoned Object'), ('license_plate', 'License Plate Detected')], default='person', max_length=20),
        ),
    ]
