# Generated by Django 6.0.7 on 2026-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_plate_number_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detected_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('person', 'Person Detected'), ('motion', 'Motion Detected'), ('abandoned_object', 'Abandoned Object'), ('license_plate', 'License Plate Detected'), ('vehicle', 'Vehicle Detected'), ('animal', 'Animal Detected')], default='person', max_length=20),
        ),
    ]
