// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACNl8xqGgVtRhL8K4YMa2saQoGsnvJpm4',
    appId: '1:98943941815:web:017888dfa5d33d9a02a132',
    messagingSenderId: '98943941815',
    projectId: 'ai-cctv-system',
    authDomain: 'ai-cctv-system.firebaseapp.com',
    storageBucket: 'ai-cctv-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtk9ABcMq2DXiJYuJ0y6eGcOd7glpfwqE',
    appId: '1:98943941815:android:f823cbd046e05dc202a132',
    messagingSenderId: '98943941815',
    projectId: 'ai-cctv-system',
    storageBucket: 'ai-cctv-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsor5sAfbGlOQw53jsh0fy-kfgpdQc42Q',
    appId: '1:98943941815:ios:f8d294c2409e96f502a132',
    messagingSenderId: '98943941815',
    projectId: 'ai-cctv-system',
    storageBucket: 'ai-cctv-system.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsor5sAfbGlOQw53jsh0fy-kfgpdQc42Q',
    appId: '1:98943941815:ios:f8d294c2409e96f502a132',
    messagingSenderId: '98943941815',
    projectId: 'ai-cctv-system',
    storageBucket: 'ai-cctv-system.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACNl8xqGgVtRhL8K4YMa2saQoGsnvJpm4',
    appId: '1:98943941815:web:966c75665915d61202a132',
    messagingSenderId: '98943941815',
    projectId: 'ai-cctv-system',
    authDomain: 'ai-cctv-system.firebaseapp.com',
    storageBucket: 'ai-cctv-system.firebasestorage.app',
  );
}
